-- Bows
DISABLE_WOODEN_BOW = false
DISABLE_LONGBOW = false
DISABLE_COMPOSITE_BOW = false
DISABLE_STEEL_BOW = false
DISABLE_COMPOUND_BOW = false

-- Crossbows
DISABLE_CROSSBOW = false
DISABLE_REPEATING_CROSSBOW = false
DISABLE_ARBALEST = false
DISABLE_AUTOMATED_ARBALEST = false

-- Special Arrows
DISABLE_TELEPORT_ARROW = false
DISABLE_DIG_ARROW = false
DISABLE_TNT_ARROW = false
DISABLE_TORCH_ARROW = false
DISABLE_ROPE_ARROW = false
DISABLE_LIGHTNING_ARROW = false

-- Fireworks arrows
DISABLE_FIREWORKS_BLUE_ARROW = false
DISABLE_FIREWORKS_RED_ARROW = false
DISABLE_FIREWORKS_GREEN_ARROW = false

-- Normal arrows
DISABLE_STONE_ARROW = false
DISABLE_STEEL_ARROW = false
DISABLE_OBSIDIAN_ARROW = false
DISABLE_DIAMOND_ARROW = false
DISABLE_MITHRIL_ARROW = false
